### ISSUE TITLE
Google Analytics Alternative suchen

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#1]
Hoi Max

Ich habe mich noch betreffend Google Analytics Alternativen schlau gemacht. Wir könnten euch [Matomo](https://matomo.org) empfehlen. Matamo könnte durch Puzzle ITC mit Datenstandort in der Schweiz betrieben werden. Den Betrieb müssten wir aber engineeren und verrechnen (Grobschätzung CHF 200.-/Monat). Falls euch der Datenstandort CH nicht so wichtig ist, würde ich empfehlen, direkt bei Matomo ein Abo für [ca. Euro 20.-/Monat](https://matomo.org/pricing/) zu lösen. Eure Analytics-Daten wären dann zwar im Ausland (glaube Neuseeland), aber gemäss [https://matomo.org/100-data-ownership/](https://matomo.org/100-data-ownership/) versprechen sie, dass die Daten zu 100% euch gehören und nicht weiterverkauft werden.

Wie siehst du das?

**Comment by maximilianstern** [comment]
super, danke! schaue ich kurz mit @MargotGagliani an!

**Comment by maximilianstern** [comment]
Lieber @bsantschi wir haben das kurz intern abgeklärt: Weil der QV der Träger ist, können wir mit einer Cloud-Lösung arbeiten (bei einer städtischen Seite würde es anders ausschauen). Wir sollten aber sicherstellen, dass die NutzerInnen dem Tracking zustimmen. Gut so für Euch?

**Comment by bsantschi** [comment]
Danke fürs Abklären, Max.

- Was machen wir mit NutzerInnen, die dem Tracking nicht zustimmen? Nicht tracken oder Teilnahme nicht zulassen? Ersteres wäre etwas aufwändiger aber wohl schon machbar.

- Werdet ihr ein Matomo Cloud-Abo lösen oder sollen wir das machen? Am liebsten per 1. März, dann könnten wir das gleich mit einbauen und testen

**Comment by maximilianstern** [comment]
Falls nicht zu aufwändig, würde ich sagen: nicht tracken.

Könnt ihr das Abo direkt lösen? ich glaube, das wäre einfacher...

**Comment by bsantschi** [comment]
Ist gut, danke für die Antworten.
