### ISSUE TITLE
Firmenlogos in Footer

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#10]
Puzzle und Logo der Grafikerfirma in den Footer aufnehmen.

**Comment by bsantschi** [comment]
Sabeth sammelt die Logos, Kabeljau erstellt danach **ein** Bild, dieses kann danach im Admin-Bereich hochgeladen werden.

**Comment by larsUE** [comment]
Hab Logobild mal hochgeladen. Skaliert jedoch zur Zeit noch nicht und ist sehr klein (auch Logo im header).

**Comment by carlobeltrame** [comment]
Das Logo im Footer wird in Decidim auf 140px Breite skaliert. Quick fix ohne Code-Änderung wäre also, die Logos untereinander statt nebeneinander zu stapeln. Aber ich finds auch eine etwas komische Wahl.

**Comment by larsUE** [comment]
Habs mal umgestellt. Sieht sogar noch schlimmer aus ;). Könnte man allenfalls das decidim logo im footer ersetzen (Helsinki hat es auch nicht), würde auch vom Ort her besser passen.

**Comment by carlobeltrame** [comment]
Ja können wir, aber das ist im Moment genau gleich auf maximal 140px beschränkt, also müssen wir so oder so eine Lösung finden.
Das Bild wird übrigens nur runterskaliert wenns grösser als 140px breit ist, aber nicht hochskaliert, daher siehts jetzt so gequetscht aus. Wenn du das Bild mit mind. 140px Breite hochlädst wirds wenigstens die volle Breite ausnutzen.

**Comment by larsUE** [comment]
Ich habs jetzt mit verschiedenen Grössen versucht, es ändert sich aber nicht wirklich was. Am schönsten fände ich, wenn alle nebeneinander im schwarzen Balken platz hätten und so als Gegengewicht zu den Social-Media-Verknüpfungen auf der rechten Seite wirken.

**Comment by carlobeltrame** [comment]
Okay, und auf Mobilgeräten die weniger horizontalen Platz haben?

**Comment by larsUE** [comment]
Uff, dann wärs wiederum schön, wenn sie sich mittig untereinander anordnen, so wie es das decidim logo bereits macht. aber dann müsste man jedes logo einzeln hochladen, oder? was denkst du?

**Comment by carlobeltrame** [comment]
Ja, automatisch auseinanderschneiden geht natürlich nicht. Aber dann wäre der Programmieraufwand höher.

Noch ein Kompromiss-Vorschlag: Wie wäre es wenn wir in einem Bild die Logos wieder rechteckig anordnen:
```
[urban equipe] [quartierverein wipkingen]
[nextzurich]   [puzzle itc]
```
Und dann versuche ich es so einzurichten:
* auf Desktop keine Breitenlimite, das Bild sollte so hoch werden wie möglich sodass es noch in den Footer passt
* auf Mobile das Bild zentrieren bzw. die volle verfügbare Breite ausnutzen

Das wäre auf jeden Fall ein weniger tiefer Eingriff in decidim als ein beliebig oft wiederholbares Logo-Felder hinzuzubauen.

**Comment by larsUE** [comment]
Ja, machen wir's doch so. Ich lade in dem Fall im Laufe des Tages mal die neue Anordnung hoch.

**Comment by larsUE** [comment]
![group2](https://user-images.githubusercontent.com/60926257/91154630-04fdb080-e6c2-11ea-818c-d62f1111249e.png)

**Comment by bsantschi** [comment]
Hey @larsUE, die Logos sehen prima aus! Ich sende dir hiermit noch unser Logo in Schwarz/Weiss zu, so wären dann alle vier einheitlich. Darf ich dich bitten das noch anzupassen?

![puzzle_classic_bg_rgb](https://user-images.githubusercontent.com/222940/93288993-77534380-f7dd-11ea-9796-18257269fe85.png)

**Comment by larsUE** [comment]
Danke! Habs ersetzt.

**Comment by larsUE** [comment]
Guete Morge! Die Logos sehen grundsätzlich sehr gut aus. Ich habe jedoch einen Bug: Und zwar wird das Logo bei einer Änderung der Bildschirmbreite verzogen. Meistens passiert das, wenn man vom mobilen One-Column Layout vergrössert.

<img width="488" alt="Bildschirmfoto 2020-09-17 um 09 16 45" src="https://user-images.githubusercontent.com/60926257/93433319-efe1ff00-f8c6-11ea-919a-faf8aa0d7e5c.png">

**Comment by carlobeltrame** [comment]
Das kann ich so nicht reproduzieren. Ich habe mit Firefox und Chromium getestet. Welchen Browser hast du verwendet?
![logos-scaling](https://user-images.githubusercontent.com/7566995/93438310-6a158200-f8cd-11ea-867a-c768c63bf561.gif)

**Comment by larsUE** [comment]
Ah, ich habs auf Safari getestet.
![safari](https://user-images.githubusercontent.com/60926257/93438806-16576880-f8ce-11ea-9d79-7ab2f4265602.gif)

**Comment by Kagemaru** [comment]
Ich hab das ganze mal auf Safari nachgestellt. Anscheinend ist das tatsächlich ein render bug in Safari. Wenn ich die Klasse auf dem container de- und aktiviere passt das Bild.

**Comment by bsantschi** [comment]
Ich finde den Bug nicht schlimm, da er nur beim Verändern der Fenstergrösse nach dem Laden der Seite auftritt. Sobald ein nächster Link angeklickt wird, sieht das Logo wieder gut aus.
