### ISSUE TITLE
Mit Barcelona abklären, ob jemand bereits 2FA implementiert hat

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#11]

**Comment by maximilianstern** [comment]
Ich werde euch hier gleich mit Arnau von Decidim Barcelona vernetzen

**Comment by carlobeltrame** [comment]
Antwort von Arnau:

> Hi Carlo,
> In Decidim you can have several authorization systems, and you configure/decide to which actions you limitate 
> Example: In Barcelona we have 2 ways to do athorization:
> - City Census (conected with  webservice calling with ID, date of birth and postal code)
> - Phone number
> Then we can limitate actions (suports, Proposal creations, endorsements, sign petitions) with the authoization that you want to apply in each action. 
> This is our 2FA but it doesn't work for the login, just for the actions that you want to limitate.
> Maybe you have more specific questions and we could have a call to solve it in more detail.
> All the best
> Arnau Monterde

**Comment by carlobeltrame** [comment]
Noch eine Antwort:
> Hi Carlo,
> I'm Andrés, one of the technical people of Decidim. Sorry for the delay answering this email.
> At the moment we don't have 2FA implemented.
> Related with this we have a Verification / Authorization integration with SMS gateways, although it's not the same (as 2FA is about Authentication). Here's the code, adapted for the provider of Barcelona City Council (Vodafone): https://github.com/AjuntamentdeBarcelona/decidim-barcelona/blob/3b5d5675f50121c6727bca0b1b8efd81b1334a83/app/services/sms_gateway.rb
> PRs/thoughts on how to implement this are welcome. I think this is specially useful for admin users.
> Regards,
