### ISSUE TITLE
Registrierung: NutzerInnen sollen Tracking zustimmen

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#16]
Decidim fragt beim ersten Aufruf bereits, ob man Cookies zulässt. Das Tracking könnte in derselben Meldung erwähnt und zugestimmt werden.

**Comment by carlobeltrame** [comment]
Ich habe die Übersetzung des Cookie-Hinweises so angepasst dass auch Matomo darin erwähnt wird:

"Diese Seite verwendet Cookies. Durch die weitere Verwendung dieser Seite stimmen Sie der Verwendung von Cookies zu. Wir verwenden Matomo für anonymisierte Statistiken. Erfahren Sie mehr darüber hier."

"This site uses cookies. By continuing to browse the site, you agree to our use of cookies. We also use Matomo for anonymous user statistics. Find out more about it here."

Der "hier" Link führt zur Seite terms-and-conditions, den Text dort drunter können Max und Sabeth selber anpassen. Ich weise daher dieses Issue euch zu.

**Comment by Sabethtoedtli** [comment]
ok. 
Kleiner Hinweis/Bitte zur Formulierung: Wir machen die ganzen Texte in DU-Form, deshalb bitte auch der Cookieshinweis in DU.

ansonsten ist gut. verlinkung zu terms & conditions auch gut.

**Comment by carlobeltrame** [comment]
Habe das kurzerhand noch geändert und auf Produktion aufgeschaltet. Somit schliesse ich dieses Ticket.
