### ISSUE TITLE
Aufbau Integrationsumgebung

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#2]
Betrieb: CloudScale
URL quartieridee.puzzle.ch
Release: nächtlich automatisch

**Comment by bsantschi** [comment]
Bitte noch URL auf quartieridee.puzzle.ch ändern.

**Comment by Kagemaru** [comment]
Subdomain wurde bei /sys angefordert

**Comment by bsantschi** [comment]
quartieridee.puzzle.ch funktioniert.
