### ISSUE TITLE
Offene Fragen betreffend Domain & DNS klären.

### ISSUE THREAD

**Issue by Kagemaru** [puzzle/quartieridee#21]
# Offene Fragen
## Wer betreut die Domain quartieridee.ch in Zukunft?
**Vorteile einer Betreuung von Puzzle:**
- Intern besser planbare Abläufe für das Aufschalten der Seite
- Einfachere Umstellung von DNS Einträgen bei nachträglichen Änderungen

**Nachteile:**
- Wenn die Domain noch anderweitig verwendet werden soll (Mail Server, Portal Seite, etc.), müssen DNS Änderungen bei Puzzle gemeldet werden.

**Comment by maximilianstern** [comment]
Ich finde den Vorschlag gut, dass Puzzle diese Domain für den Zeitraum des Projekts betreut. @Sabethtoedtli ist das für dich auch in Ordnung?

**Comment by Sabethtoedtli** [comment]
ist für mich in Ordnung.  
Was muss ich dafür tun?
Allerdings: Es läuft tatsächlich auch noch eine Mailadresse mit  der Domain  über via Hostpoint,  wo ich die Domain momentan habe: frage@quartieridee.ch > diese würde ich gerne behalten um von dieser Adresse zukünftig auch Newsletter  verschicken  zu können.

**Comment by Kagemaru** [comment]
Wir können DNS Einstellungen für mails und die subdomain mail.quartieridee.ch und/oder webmail.quartieridee.ch auf HostPoint weiterleiten.

Den Ablauf der Übernahme frage ich intern noch nach und melde mich wieder.

**Comment by Kagemaru** [comment]
Unsere system engineers sagen es wäre bei einer bestehenden E-Mail Adresse auf HostPoint einfacher, wenn wir ein Login bei HostPoint haben könnten und die DNS Einstellungen dort selber managen können. Dies ermöglicht die gleichen Vorteile (koordinierte Umschaltung, nachträgliche Änderungen), aber lässt die Verwaltung der Mail Adressen in eurer Hand.

Wäre es daher möglich ein HostPoint Konto für uns zu erstellen?

**Comment by maximilianstern** [comment]
Finde ich gut, würde aber vorschlagen, dass @Sabethtoedtli das übernimmt.

**Comment by Sabethtoedtli** [comment]
Mach ich. Auf welche eurer mailadressen?

**Comment by Kagemaru** [comment]
burkhalter@puzzle.ch ist meine und beltrame@puzzle.ch ist die von Carlo

**Comment by Sabethtoedtli** [comment]
Das hat geklappt, oder? @carlobeltrame 
Nur weil Max heute am Telefon meinte, Bruno habe ihm gesagt ihr bräuchtet dann noch was wegen der Domain von uns... Falls dies der Fall ist, müsstet ihr das mit mir klären. merci

**Comment by carlobeltrame** [comment]
Es sind keine offenen Fragen mehr. Aber der Go-Live ist mit einer DNS-Änderung verbunden, sodass man schlussendlich unter quartieridee.ch nicht mehr auf die Landing Page sondern auf die Decidim-Webseite gelangt. Das könnt ihr oder wir machen, was euch lieber ist.
