### ISSUE TITLE
Logo-Upload fixen

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/quartieridee#24]
Wenn unter https://pitc-quartieridee-int.ocp.puzzle.ch/admin/organization/appearance/edit in den vier Logo-Feldern eine Datei hochgeladen wird, ist diese nachher nicht unter dem generierten Asset-Pfad erreichbar.

**Comment by Kagemaru** [comment]
Das Problem war, dass der Webserver (nginx), nur bestehende Static Assets ausgeliefert hat und die Bilder noch nicht. Dies wurde auf seiten Openshift behoben.
