### ISSUE TITLE
Übersetzungen und Begriffe anpassen

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/quartieridee#25]
Die deutsche Übersetzung scheint mit automatischen Tools gemacht worden zu sein. Zum Beispiel wurde das englische Label des Feldes "Order by" mit "Bestellvorschläge von" statt "Sortieren nach" übersetzt.
Primär sollten wir das bei uns fixen, möglicherweise könnten wir das aber auch gleich auf Crowdin oder als PR im zentralen Decidim-Projekt machen.

**Comment by Sabethtoedtli** [comment]
Wir haben diesbezüglich auch schon diverse Begriffe/Titel/Buttons entdeckt, die wir gerne besser übersetzen oder gänzlich umbenennen möchten. 
Wie wollen wir dabei vorgehen? Sollen wir euch eine möglichst vollständige Liste schicken, wenn wir diese parat haben?

**Comment by carlobeltrame** [comment]
Ich fände es sinnvoll wenn wir an einem Ort eine möglichst vollständige Liste haben in der diese Begriffe gesammelt werden. So behalten wir den Überblick über die Änderungen, und ich könnte die Korrekturen in Zukunft dem Decidim-Team als Verbesserung der offiziellen Decidim-Übersetzungen vorschlagen.
Ihr könnt diese Liste aber auch laufend ergänzen wenn euch später noch weiteres auffällt.

**Comment by Sabethtoedtli** [comment]
Wir fangen morgen mit dieser Liste an. 
Dazu noch eine Frage an dich: 
Wie ist es für dich am einfachsten? Alphabetisch oder gar nicht sortiert?
Oder nach Seiten sortiert, wo die Begriffe/Sätze vorkommen?
Oder anders?

**Comment by Sabethtoedtli** [comment]
Voilà!
Wir haben eine Liste zusammengestellt, mit Begriffen/Sätzen die im Deutschen (und teilweise auch nochmals im Englischen) angepasst werden müssen.
https://docs.google.com/spreadsheets/d/18DArYl7QbAz2MrWylYTPOfNobhxMaL4b2HO9Mf-wveU/edit?usp=sharing
Gelber Highlight bedeutet, dass es nicht nur eine sprachliche, sondern auch eine funktionale Anpassung benötigt, oder wir eine weitergehende Erklärung brauchen... entsprechende Hinweise finden sich jeweils in der Kommentarspalte.
Diese Liste ist vermutlich noch nicht komplett vollständig, beinhaltet aber alles, was wir bisher gefunden haben. Gib uns bitte Bescheid, wenn alle diese Dinge angepasst sind, sodass wir dann nochmals die ganze Website nach letzten Unklarkeiten/Fehlübersetzungen absuchen können. 
Und sowieso: Jederzeit fragen wenn was unklar ist. Hier oder per Mail (an Lars oder mich oder  beide).
Merci!

**Comment by Sabethtoedtli** [comment]
und zur info: 
Es kommen dann noch wenige Einstellungs-Änderungswünsche. 
Allerdings erst, wenn wir wissen WELCHES unser erstes Testprojekt wird. Und ob das Wipkingen wird oder nicht, das wissen wir erst Mitte nächster Woche.

**Comment by carlobeltrame** [comment]
Ich habe die Liste durchgearbeitet und soweit möglich eingebaut. Wo ich die Änderungen nicht genau wie spezifiziert umsetzen konnte habe ich in rot Notizen in die Kommentarspalte gemacht.
Das Ganze ist jetzt auf der Produktion deployed und bereit dass ihr es nochmals durchschauen könnt.

**Comment by Sabethtoedtli** [comment]
Danke für die Bearbeitung.
Die meisten deiner  Vorschläge finden wir für den Moment ok  (z.b. "Vorschlag"  als Terminologie  zu lassen, und (noch)  nicht zu  "Idee" abzuändern.)
Einige wenige Dinge  haben wir noch ergänzt oder aufgrund deiner Kommentare angepasst. Du findest sie in derselben [Tabelle](https://docs.google.com/spreadsheets/d/18DArYl7QbAz2MrWylYTPOfNobhxMaL4b2HO9Mf-wveU/edit?usp=sharing):  >> türkis markiert. 
Alles andere (ohne markierung oder gelbe markierung) kannst du ignorieren.

Merci!

**Comment by carlobeltrame** [comment]
Sind alle 3 Punkte erledigt.

**Comment by larsUE** [comment]
Hoihoi! Es sind noch Textfehler (insbesondere in den Mails) aufgetaucht, die möglichst bald geflickt werden müssen. @carlobeltrame oder @Kagemaru : kommt da jemand mal dazu?

**E-Mails**
![image (1)](https://user-images.githubusercontent.com/60926257/94025423-c50d1480-fdb8-11ea-8fe6-1a8e0428a197.png)
Neu:
>Ein Administrator der Gruppe XX hat dich einzuladen der Gruppe XX beizutreten.
>Du hast diese Benachrichtung erhalten, weil du einer Gruppe eingeladen wurdest. Überprüfe den Tab "Gruppen" in deinem >Profil, um die Einladung zu akzeptieren._

![image (2)](https://user-images.githubusercontent.com/60926257/94025753-26cd7e80-fdb9-11ea-95d7-958c355849d5.png)
Neu: 
>Willkommen [E-Mail]
>Du kannst deine E-Mail-Adresse über folgenden Link bestätigen:
>Mein Konto bestätigen

![WhatsApp Image 2020-09-23 at 15 49 39](https://user-images.githubusercontent.com/60926257/94026279-be32d180-fdb9-11ea-9d67-366b5b2b80e6.jpeg)
Neu:
>Hallo NAME
>Eine Änderung wurde für "IDEE" vorgeschlagen
>Du kannst sie hier überprüfen:
> IDEE-LINK
>Du hast diese Benachrichtigung erhalten, weil du dieser Idee folgst.

<img width="609" alt="Bildschirmfoto 2020-09-23 um 16 39 35" src="https://user-images.githubusercontent.com/60926257/94027662-5ed5c100-fdbb-11ea-8615-81624294a2b9.png">
Neu:
>Hallo NAME
>Eine Änderung wurde für "IDEE" vorgeschlagen
>Du kannst sie hier überprüfen:
> IDEE-LINK
>Du hast diese Benachrichtigung erhalten, weil du dieser Idee folgst.

**Frontend**
![image (3)](https://user-images.githubusercontent.com/60926257/94025990-698f5680-fdb9-11ea-80aa-6b8637170bc2.png)
Neu: 
> Melde dich mit deinem Konto an oder registriere dich, um diesen Beitrag zu kommentieren.
>Hallo NAME
>Eine Änderung wurde für "IDEE" vorgeschlagen
>Du kannst sie hier überprüfen:
>IDEE-LINK
>Du hast diese Benachrichtigung erhalten, weil du der*die Autor*in der Idee bist.

**Comment by larsUE** [comment]
![Bild von iOS (1)](https://user-images.githubusercontent.com/60926257/94394527-dc078a00-015d-11eb-83c8-835696d1f0d3.png)
Neu:
>Hallo [Name],
>Das Thema «Plattformfeedback» wurde kommentiert:
>
>[Inhalt]
>Link zum Thema
>
>Du hast diese Benachrichtigung erhalten, weil du das Thema «Plattformfeedback» oder dem*r Autor*in folgst. Wenn du diese Nachrichten nicht mehr erhalten möchtest, kannst du sie unter dem angegeben Link entfolgen.

<img width="885" alt="Bildschirmfoto 2020-09-28 um 07 47 57" src="https://user-images.githubusercontent.com/60926257/94395073-1aea0f80-015f-11eb-8a8c-0e78603074d3.png">

Hier fehlt die Übersetzung.
Neu:
>Antworten verbergen

**Comment by larsUE** [comment]
Im Newsletter:

<img width="615" alt="Bildschirmfoto 2020-09-29 um 12 17 48" src="https://user-images.githubusercontent.com/60926257/94546226-e1440200-024d-11eb-9691-efba7c5b5bd8.png">
Neu:
>Falls die E-Mail nicht richtig angezeigt wird, kannst du es auf der Website anschauen.


<img width="615" alt="Bildschirmfoto 2020-09-29 um 12 20 15" src="https://user-images.githubusercontent.com/60926257/94546413-236d4380-024e-11eb-95e3-d09b3e2d071b.png">
Neu:
>Du hast diese E-Mail erhalten, weil du den Quartieridee-Newsletter abonniert hast. Du kannst deine Einstellungen auf deiner Benachrichtigungsseite ändern. Wenn du diese E-Mail nicht mehr erhalten möchtest, kannst du sie hier abbestellen.

**Comment by larsUE** [comment]
![image (4)](https://user-images.githubusercontent.com/60926257/94654898-114ade00-02fe-11eb-99a5-409764d643cd.png)
Neu:
>Hallo Sabeth
>
>Der Vorschlag "XX" wurde zu "Quartieridee Wipkingen" hinzugefügt.
>[Ideentext]
>[Link]
>Du hast diese Benachrichtigung erhalten, weil du "Quartieridee Wipkingen" folgst. Wenn du diese Nachrichten nicht mehr erhalten möchtest, kannst du sie unter dem angegeben Link entfolgen.

**Comment by larsUE** [comment]
![image (5)](https://user-images.githubusercontent.com/60926257/94680338-e5415400-0321-11eb-98af-e0a07f39cd9a.png)
Neu:
>Du musst dich anmelden oder registrieren, bevor du fortfahren kannst.

**Comment by Kagemaru** [comment]
Die neuen Übersetzungen wurden soeben auf die Integration deployed. Bereit zum testen.

@carlobeltrame
Bei den Kommentaren wenn man nicht eingeloggt ist greift die Übersetzung nicht.
Da müssen wir schauen wie man die Javascript files die Übersetzungen enthalten neu kompiliert beim deployen.
Kurzfristig habe ich die Übersetzung im bundle.js/bundle.js.map geändert.

**Comment by bsantschi** [comment]
@larsUE könntest du die Übersetzungen auf der [Integrationsumgebung](https://quartieridee.puzzle.ch) testen bevor wir sie auf die Produktion einspielen?

**Comment by larsUE** [comment]
Hab ich gemacht! Folgendes ist mir aufgefallen:

- der hide_replies text in der Kommentarspalte steht bei mir immer noch
- die "Sie müssen sich anmelden oder registrieren" ist immer noch in Sie-Form
- Das Mail zur neuen Version sieht noch so aus, Vorschlag steht auch oben. <img width="580" alt="Bildschirmfoto 2020-10-09 um 08 49 36" src="https://user-images.githubusercontent.com/60926257/95552097-6082c400-0a0c-11eb-999b-7d8d73f49647.png">

Ich konnte aber ehrlicherweise auch nicht alle E-Mails reproduzieren, da gibt es so viele. Es kann auch sein, dass obiger Screenshot nicht das gleiche Mail ist wie vorhin gemeldet, und da wird es auch noch weitere geben. @carlobeltrame bzw. @Kagemaru : Sind die Mail-Texte nicht irgendwo in einem File gespeichert? Dann könnten auch @Sabethtoedtli und ich mal alle überfliegen und korrigieren, damit ihr es dann nur noch zu committen bräuchtet.  
.

**Comment by Kagemaru** [comment]
@larsUE
 
  - hide_replies:
    - Bereits übersetzt, aber wird nicht angezeigt [link](https://github.com/puzzle/quartieridee/blob/7efc5b41e53116e82215a32cae43d7ae5b70459c/config/locales/de.yml#L248)
     - Eventuell das gleiche Problem wie mit Anmeldetext
   - Anmeldetext:
     - Bereits übersetzt, aber wird nicht angezeigt [link](https://github.com/puzzle/quartieridee/blob/7efc5b41e53116e82215a32cae43d7ae5b70459c/config/locales/de.yml#L303)
     - Diese Übersetzung ist in ein kompiliertes Javascript file integriert und ignoriert deshalb unsere Übersetzungen. Siehe [Kommentar](https://github.com/puzzle/quartieridee/issues/25#issuecomment-704893257) an @carlobeltrame 
   - Mail Template
     - Bereits übersetzt, evtl andere Mail? Oder andere Userkategorie.
       - [affected_user](https://github.com/puzzle/quartieridee/blob/7efc5b41e53116e82215a32cae43d7ae5b70459c/config/locales/de.yml#L341)
       - [follower](https://github.com/puzzle/quartieridee/blob/7efc5b41e53116e82215a32cae43d7ae5b70459c/config/locales/de.yml#L346)
 
Bereits übersetzte Texte findet ihr in diesem [File](https://github.com/puzzle/quartieridee/blob/master/config/locales/de.yml).
Für neue Übersetzungen gibt es leider kein Zentrales File. Für diese muss man das zugehörige Modul nach der Übersetzung durchsuchen.
  
Unser Ablauf für neue Übersetzungen:

  1. Alle installierten Gems durchsuchen und herausfinden in welchem Modul es übersetzt wurde
  2. Yaml Struktur extrahieren
  3. In Struktur von unserem Übersetzungsfile integrieren
  4. Übersetzen

**Comment by larsUE** [comment]
mit dem Term-Customizer könner wir das nun selbst machen https://github.com/puzzle/quartieridee/actions/runs/349491710
