### ISSUE TITLE
Bilder auf Vorschlägen -> herausfinden wie

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/quartieridee#30]
Beispiel wie es aussehen kann bei Decidim Barcelona:
https://www.decidim.barcelona/assemblies/BCNdesdecasa/f/3830/

**Comment by carlobeltrame** [comment]
Ich habe nachgeforscht und dieses Feature wurde erst [Ende Februar 2020](https://github.com/decidim/decidim/pull/5640) fertig gestellt. Barcelona setzt eine neuere Version von Decidim ein als wir das bisher taten. Ich habe nun diese neue Version auch bei uns auf Integration aufgeschaltet. 

Dabei ist mir leider zwischenzeitlich ein Fehler passiert, und ich musste auf der Integration alle Inhalte löschen. Ich habe allen involvierten deshalb nun neue Account-Einladungen gesendet.

Beispiel wie das bei uns aussehen kann: https://quartieridee.puzzle.ch/processes/quartierideeWipkingen/f/1/

Auf Produktion kommt dieses neue Feature erst wenn wir das nächste Mal das den aktuellen Stand des Codes einspielen, da warte ich auf euer Kommando dafür.

**Comment by bsantschi** [comment]
Sieht toll aus!

Beim Überführen dieses Features auf die Produktion dürfen die Inhalte aber nicht verloren gehen. Kriegen wir das hin?

**Comment by carlobeltrame** [comment]
Das muss auf Produktion unbedingt ohne Datenverlust gehen, ja. Dafür teste ich das ja auf Integration zuerst durch. Und Notfalls hätten wir auch noch ein Backup, mit dem wir den Stand der Einstellungen auf Produktion wiederherstellen könnten, sollte doch noch etwas unerwartetes auftreten.

**Comment by carlobeltrame** [comment]
Habe es auf Produktion deployed, gab keine Probleme soweit ich sehe.
