### ISSUE TITLE
Menü/Hierarchie-Anpassungen

### ISSUE THREAD

**Issue by Sabethtoedtli** [puzzle/quartieridee#32]
1. Lässt sich die Beteiligungsprozess-übersichts-Seite (https://pitc-stzh-quartieridee-prod.appuioapp.ch/processes) ausblenden, sodass man dort direkt auf den aktuellen Prozess weitergeleitet wird (https://pitc-stzh-quartieridee-prod.appuioapp.ch/processes/quartieridee2020), falls es nur einen gibt? Es ist sonst ein Schritt zuviel, der vor allem verwirrt und ausbremst und keine zusätzlichen Infos enthält?

2. Lassen sich die Tabs BLOG und EVENTS aus dem Untermenu des Beteiligungsprozesses in die obere Ebene verschieben, sodass sie im Overall-menu zwischen dem TAb "beteiligungsprozesse" und "hilfe" zu stehen bekommen?

3. Lässt sich innerhalb des Beteiligungsprozesses der Tab "prozess" ausblenden? den brauchen wir eigentlich nicht und er bietet keinen Mehrwert.

4. Lässt sich innerhalb des Beteiligungsprozesses die Reihenfolge der Tabs verändern, bzw. beeinflussen, welcher standartmässig als erster angezeigt wird? > das wäre sehr hilfreich, um je nach Phase eine andere Priorität zu setzen. 

5. Bitte folgende Begriffe ändern im Hauptmenü:
Beteiligungsprozese > neu: Mitmachen
Hilfe > neu: Informationen

**Comment by carlobeltrame** [comment]
All diese Dinge sind möglich. Untenstehend meine Aufwandschätzungen für Umsetzung plus einmalige, gemeinsame Aufschaltung, sowie technische Notizen zur Umsetzung. Alles in allem schätzungsweise 1.5 PT.

1. Schätzung 3 Stunden
    - `ParticipatoryProcessesController#index` überschreiben sodass auf den Prozess weitergeleitet wird wenn nur einer veröffentlicht ist
2. Schätzung 5 Stunden
    - Nur falls der User gerade einen Prozess ansieht, Hauptmenüeintrage einfügen [wie das schon in Participatory Processes gemacht wird](https://github.com/decidim/decidim/blob/develop/decidim-participatory_processes/lib/decidim/participatory_processes/engine.rb#L65)
    - Elemente aus Tab-Bar entfernen indem [_process_navigation.html.erb](https://github.com/decidim/decidim/blob/develop/decidim-participatory_processes/app/views/layouts/decidim/_process_navigation.html.erb) überschrieben wird
3. Schätzung 4 Stunden
    - Element aus Tab-Bar entfernen indem [_process_navigation.html.erb](https://github.com/decidim/decidim/blob/develop/decidim-participatory_processes/app/views/layouts/decidim/_process_navigation.html.erb) überschrieben wird
    - `ParticipatoryProcessesController#show` überschreiben sodass auf die Komponente (Tab) weitergeleitet wird welche das niedrigste "weight" hat. 
4. Die Reihenfolge könnt ihr selber anpassen: Die "Tabs" sind die Komponenten die ihr zum Participatory Process hinzufügt. Auf jeder solchen Komponente kann man eine Zahl "Reihenfolge" bzw. "Weight" setzen. Das erste Tab "Der Prozess" ist zwar fix das erste, aber das entfernen wir ja unter Punkt 3. Die Reihenfolge der Komponenten wird übrigens auch im [Admin-Backend](https://quartieridee.puzzle.ch/admin/participatory_processes/quartieridee2020/components) angewendet.
5. Machen wir im Rahmen von #25, am besten dort auf die Liste aufnehmen
