### ISSUE TITLE
DNS umstellen

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#34]
www.quartieridee.ch auf Decidim umstellen.

**Comment by bsantschi** [comment]
Lars: Ziel am 16.9 Launch/Transfer der Website

**Comment by bsantschi** [comment]
Hoi @Kagemaru @carlobeltrame, bitte Umstellung zusammen vorbereiten, Thomas ist am 16.9 in den Ferien.

**Comment by larsUE** [comment]
hoi @carlobeltrame! hab kurz nach Mittag gesehen, dass die umstellung funktioniert hatte. Jetzt läuft aber gar nichts mehr. Bist du noch dran?

**Comment by carlobeltrame** [comment]
@larsUE Wir haben inzwischen https://quartieridee.ch am laufen, schauen aber noch mit unseren Infrastruktur-Partnern wegen https://www.quartieridee.ch (mit www) dass das auch noch läuft. Du kannst ab jetzt auf der URL ohne www zu testen beginnen.

**Comment by larsUE** [comment]
Yeah! Super, danke dir!

**Comment by carlobeltrame** [comment]
Inzwischen funktioniert beides; www leitet automatisch auf die Variante ohne www weiter.
