### ISSUE TITLE
Monitoring der Umgebungen in Ruby Apps Dashboard aufnehmen

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#35]

**Comment by Kagemaru** [comment]
Die Felder sind drin, bei den Daten stimmt noch was nicht. Anfrage bei /sys ist noch offen.

**Comment by Kagemaru** [comment]
Wochenverantwortlicher funktioniert, Backup status auch.
HTTP Status soll in der nächsten Stunde dazukommen.

**Comment by Kagemaru** [comment]
Dashboard online: https://grafana.puzzle.ch/d/wd5uyCaWz/ruby-apps-ng
