### ISSUE TITLE
Aufbau Produktionsumgebung

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#4]
Betrieb: APPUiO
URL: www.quartieridee.ch
Release: manuell bei Bedarf
Backup: nächtlich DB+Filesystem
Monitoring: Auf Puzzle Dashboard
Tracking: Matomo einrichten
SSL-Zertifikat: bereits vorhanden (https://quartieridee.ch)

**Comment by Kagemaru** [comment]
Monitoring: prometheus_exporter à la PTime in eigenem Pod

**Comment by bsantschi** [comment]
Gemäss Thomas ist nur noch die DNS-Umstellung offen. Da wir das GO zur Umstellung noch nicht haben, erstelle ich dazu ein separates Ticket.
