### ISSUE TITLE
Fehlerhaftes Karten-Icon bei Ideeneingabe

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#46]

**Comment by carlobeltrame** [comment]
Es hat sich herausgestellt, dass das kein Icon hätte sein sollen, sondern eine (statische) Karte, die anzeigt wo sich die Adresse des Vorschlags befindet. Ich habe daher auch hier wieder eine swisstopo-Karte eingefügt, die nur den Vorschlag anzeigt.

Die Änderungen sind live auf der Integrationsumgebung und Produktion.
