### ISSUE TITLE
Seite "Beteiligungsprozesse" (mit der Ansicht verschiedener Prozesse) überspringen, wenn nur ein Prozess aktiv ist

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#47]

**Comment by Kagemaru** [comment]
@carlobeltrame Können wir uns den Commit [c7273c8](https://github.com/puzzle/quartieridee/commit/c7273c8db2b5f8d766c54e528faca987f39c8e6a )nächste Woche noch zusammen anschauen?

**Comment by larsUE** [comment]
@Kagemaru @carlobeltrame Was denkt Ihr, wäre das eine Änderung, die man Meta-Decidim zur Verfügung stellen könnte?

**Comment by carlobeltrame** [comment]
Wir könntens mal versuchen. Vielleicht müsste man es aber konfigurierbar machen, da die Prozess-Liste möglicherweise noch andere Informationen enthalten kann die sonst nirgends auftauchen. Ausserdem heisst der Menüpunkt im Hauptmenü ja "Übersicht Beteiligungsprozesse". Aber für kleine Gruppierungen die decidim zum ersten Mal nutzen könnte es durchaus nützlich sein.
