### ISSUE TITLE
Änderungsantrag annehmen führt zu Fehler

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#49]

**Comment by Kagemaru** [comment]
@bsantschi Wem ist dieses Verhalten aufgefallen? Ich bräuchte eine genauere Beschreibung, da ich das Verhalten nicht nachstellen kann.

**Comment by bsantschi** [comment]
Hoi @larsUE und @Sabethtoedtli, könnt ihr uns ein Beispiel nennen, bei welchem Änderungsantrag es zu einem Serverfehler führte?

**Comment by larsUE** [comment]
@Kagemaru Wenn ich bei Änderungsvorschlag beim letzten Schritt auf "Veröffentlichen" clicke, kommt bei mir die Fehlermeldung (siehe Screenshot). Soweit ich es sehe wurde die Änderung jedoch erfolgreich publiziert -> deshalb vielleicht ein Fehler mit der URL/dem Redirect?
<img width="1674" alt="Bildschirmfoto 2020-09-01 um 09 16 13" src="https://user-images.githubusercontent.com/60926257/91814090-e9e7ef00-ec33-11ea-8cc3-e4fddb7921af.png">

BTW: Bei den Notifizierungen zu den Änderungsvorschlägen stimmen die Übersetzungen noch nicht (im Dok sind Sie jedoch grün). Sind die auf der Integrationsumgebung geflickt?
<img width="1674" alt="Bildschirmfoto 2020-09-01 um 09 18 45" src="https://user-images.githubusercontent.com/60926257/91814435-68dd2780-ec34-11ea-8217-d4ecced6699b.png">

**Comment by Kagemaru** [comment]
Zu Punkt 1: Dies ist bei mir nicht so aufgetreten, ich probiere noch ein par Szenarien durch.

Zu Punkt 2: Die Changes sind auf der Integrationsumgebung und sobald wir ein OK für ein Ticket bekommen, packen wir es auf die Produktionsumgebung. Dies mindert das Risiko, dass ein Bug sich auf PROD einschleicht.

**Comment by Kagemaru** [comment]
Die deutschen Übersetzungen von decidim-proposals waren unvollständig und haben an mehreren Orten zu Abstürzen geführt. Ich habe sie nun bei uns ergänzt und werde ein Ticket bei MetaDecidim eröffnen.

**Comment by larsUE** [comment]
geflickt gemeinsam mit #63
