### ISSUE TITLE
Weitere Textänderungen in Absprache mit Lars/Sabeth

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#51]
https://docs.google.com/spreadsheets/d/18DArYl7QbAz2MrWylYTPOfNobhxMaL4b2HO9Mf-wveU/edit?usp=sharing

**Comment by larsUE** [comment]
Alle Änderungen sind in bestehender Code-Liste gelb angestrichen.

**Comment by Kagemaru** [comment]
Ich habe mal alles umgesetzt was ich konnte. Erledigte Übersetzungen sind nun grün. Einige Übersetzungen habe ich mit Feedback ergänzt.

**Comment by larsUE** [comment]
Wir haben heute beim Testing noch zwei Notifizierungen bemerkt, die noch in "Sie"-Form sind. Könntet Ihr die ändern auf "Dein Konto wurde erfolgreich aktualisiert." und "Herzlich willkommen! Du hast dich erfolgreich angemeldet!"

<img width="488" alt="Bildschirmfoto 2020-09-17 um 14 39 09" src="https://user-images.githubusercontent.com/60926257/93471484-b07dd780-f8f3-11ea-9267-b173ec6a00fd.png">
<img width="488" alt="Bildschirmfoto 2020-09-17 um 12 38 07" src="https://user-images.githubusercontent.com/60926257/93471488-b1af0480-f8f3-11ea-9811-46e19d01aa7c.png">

**Comment by Kagemaru** [comment]
Ist übersetzt und auf INT/PROD deployed.
