### ISSUE TITLE
Grafische Anpassungen mit Christof

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#52]

**Comment by carlobeltrame** [comment]
Folgende Schritte wurden unternommen:
* [x] Noch mehr Farben wurden anpassbar gemacht, an den meisten Orten war entweder die Sekundärfarbe oder eine Schattierung davon noch hard-coded. Allerdings kann ich nicht zu 100% überall die konfigurierbaren Farben einsetzen, bis das eingesetzte Foundation Framework die CSS-Variabeln überall unterstützt (https://github.com/foundation/foundation-sites/issues/11847#issuecomment-630076278)
* [x] Terms of Service ablehnen Button zum "outlined" Style geändert
* [x] Floating help Bubbles sind jetzt per default geschlossen (am rechten Bildschirmrand)
* [x] Vorschläge übernehmen in der Liste jetzt standardmässig das Home-Bild des Prozesses, wenn sie kein eigenes Bild haben. Gleichermassen übernehmen Prozesse in der Prozess-Liste standardmässig das "highlighted_content_banner_image" der Organisation, wenn sie kein eigenes Bild definiert haben (das funktioniert auch wenn der Highlighted Content Banner ausgeschaltet ist).

Die Änderungen sind live auf der Integrationsumgebung und Produktion.
