### ISSUE TITLE
Einzelveranstaltung führt zu Fehlermeldung

### ISSUE THREAD

**Issue by larsUE** [puzzle/quartieridee#55]
Wenn ich auf "Der Prozess" oder auf der Event-Seite einen Einzelevent auswähle, lande ich immer auf der "Auf unserem Server ist ein Problem aufgetreten" Seite.

**Comment by Kagemaru** [comment]
Dies war ein Bug mit der Kartenimplementierung. Sollte auf der Integration nun gelöst sein.
