### ISSUE TITLE
bug im registrierungsfenster

### ISSUE THREAD

**Issue by larsUE** [puzzle/quartieridee#56]
Je nach Breite des Tabs verschiebt sich das @ beim Spitzname auf die nächste Zeile.

<img width="640" alt="Bildschirmfoto 2020-08-25 um 11 32 27" src="https://user-images.githubusercontent.com/60926257/91158334-c4546600-e6c6-11ea-9548-6df9860d870f.png">

**Comment by Kagemaru** [comment]
Dies ist ein Bug im Design von Decidim. Ich habe es gemeldet auf [MetaDecidim](https://meta.decidim.org/processes/bug-report/f/210/proposals/15682)
Temporär bei uns gelöst und auf INT deployed.

**Comment by larsUE** [comment]
@Kagemaru wurde jetzt [geflickt](https://github.com/decidim/decidim/pull/6649). Bei uns ist die Höhe der Felder noch verschieden? Wirkt da noch dein temp-fix?

<img width="556" alt="Bildschirmfoto 2021-01-13 um 08 50 51" src="https://user-images.githubusercontent.com/60926257/104422015-71e3eb00-557c-11eb-8243-213193f91884.png">
