### ISSUE TITLE
Karte nicht ersichtlich

### ISSUE THREAD

**Issue by larsUE** [puzzle/quartieridee#57]
<img width="1277" alt="Bildschirmfoto 2020-08-28 um 09 24 36" src="https://user-images.githubusercontent.com/60926257/91533568-63b86980-e910-11ea-919a-e38456001e95.png">
nicht sichtbar

**Comment by carlobeltrame** [comment]
Das hängt wohl mit https://github.com/puzzle/quartieridee/issues/6#issuecomment-625322582 zusammen. Der offiziell gemeldete "Owner" von puzzle.ch (Marcel Groner) muss hier bei swisstopo anfragen.

**Comment by bsantschi** [comment]
@carlobeltrame könntest du Marcel kurz beschreiben, was er machen soll? Das käme ja künftig auch anderen Decidim Instanzen auf puzzle.ch zu gute.

**Comment by carlobeltrame** [comment]
Ist behoben, Karten funktionieren wieder, auch auf unseren Domains.

> Sehr geehrter Herr Groner
> 
> Der WMTS-Dienst wurde für Ihre Webseiten puzzle.ch und appuioapp.ch freigeschaltet. Ihr Guthaben beträgt 25'000 Megapixel und ist gültig bis am 01.08.2021. Die Autorisierung wird nicht auf Stufe Subdomain vorgenommen.
> 
> Bitte nehmen Sie zur Kenntnis, dass nicht gebrauchte Megapixel am Ablaufdatum verfallen. Das Verfallsdatum wird bei jeder Guthabenerhöhung verlängert.
> 
> Bei Fragen stehe ich Ihnen gerne zur Verfügung.
> 
> Freundliche Grüsse
> 
> -----------------------------------------------------------------------------------------------
> B.Sc. Christian Kühni
> Sachbearbeiter Geodatenabgabe
> 
> Eidgenössisches Departement für Verteidigung,
> Bevölkerungsschutz und Sport VBS
> Bundesamt für Landestopografie swisstopo
> Geodatenabgabe
