### ISSUE TITLE
Kartenmodul

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#6]
Ideen auf einer Karte (z.B. swisstopo) geographisch darstellen.

**Comment by Kagemaru** [comment]
In Decidim gibt es eine Möglichkeit Geocoding zu aktivieren:
https://github.com/decidim/decidim/blob/master/docs/services/geocoding.md

Wie dies in Verwendung genau aussieht ist noch unklar.
Bei der Umsetzung wird wahrscheinlich noch ein eigener Tile Server nötig sein.

**Comment by carlobeltrame** [comment]
Die Here.com-Karte die in Decidim eingebaut ist verwendet die veraltete Here APP_CODE Autentifizierung, welche neuen Kunden bei Here.com nicht mehr angeboten wird. Es werden in Decidim zwei Services von Here.com bezogen:
* **Geocoding**: Der User gibt in Decidim nur eine Adresse ein. Diese muss dann in Koordinaten umgerechnet werden. Statt here.com habe ich nun den [Nominatim](https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md#nominatim-nominatim) Service angebunden. Dieser Service ist gratis und braucht keine Registrierung, erlaubt aber nur 1 Geocoding-Anfrage pro Sekunde. Da das Geocoding direkt beim Erstellen eines Quartieridee-Vorschlags gemacht wird, sollte das denke ich kein Problem sein.
* **Karte**: Ich habe die Karte von Here.com auf Swisstopo-Karten umgestellt. Damit diese auf der Webseite funktioniert muss man sich [hier bei Swisstopo](https://www.geo.admin.ch/de/geo-services/geo-services/portrayal-services-web-mapping/programming-interface-api/order_form.html) registrieren. Ich schlage vor dass @Sabethtoedtli und @maximilianstern das übernehmen. Als Domäne würde ich primär quartieridee.ch eintragen, und zusätzlich die vorläufige Produktions-URL und die Integrations-URL angeben (mehrere URLs kann man im Zweck-Feld angeben, habe das auch schon so gemacht).

Gebt mir Bescheid wenn ihr die swisstopo-Registrierung gemacht habt, dann deploye ich die Karte in Integration und Produktion.

**Comment by maximilianstern** [comment]
Super, vielen Dank, denke es macht Sinn wenn @Sabethtoedtli direkt die Registrierung macht.

**Comment by Sabethtoedtli** [comment]
machen wir. bzw. haben wir Anfang der Woche gemacht, aber noch keine Freischaltungs-Email bekommen. Ich  hab's jetzt nochmal versucht. Melde mich, sobald was zurück kommt.

**Comment by Sabethtoedtli** [comment]
sollte jetzt geklappt haben!

Mail von swisstopo:

_"Sehr geehrte Frau Tödtli 
Der WMTS-Dienst wurde für Ihre Website quartieridee.ch freigeschaltet. Ihr Guthaben beträgt 25'000 Megapixel und ist gültig bis am 01.04.2021.
Bitte nehmen Sie zur Kenntnis, dass nicht gebrauchte Megapixel am Ablaufdatum verfallen. Das Verfallsdatum wird bei jeder Guthabenerhöhung verlängert.
Bei Fragen stehe ich Ihnen gerne zur Verfügung."_

**Comment by carlobeltrame** [comment]
Habe die Kartenfunktion auf Produktion aufgeschaltet und ein Beispiel in der Plattformdemo erfasst.

**Comment by Sabethtoedtli** [comment]
kleiner nachtrag zur kartenfunktion auf produktions- und integrationsumgebung: 
_"Leider kann ich Ihnen diese beide Domänen nicht freischalten, da Sie nicht die registrierten Eigentümer der Domänen sind. Für Entwicklung und Testzwecke ist Localhost jedoch unbeschränkt freigeschalten."_
