### ISSUE TITLE
Nickname prefix wraps on certain view widths

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#60]
Unser [Workaround](https://github.com/puzzle/quartieridee/commit/225592c17dd7b7051ce67978876160c9b0bc69e7) ersetzen, sobald MetaDecidim unser [Bugreport](https://meta.decidim.org/processes/bug-report/f/210/proposals/15682) umgesetzt hat.

**Comment by larsUE** [comment]
wird in #56 behandelt
