### ISSUE TITLE
Falsche Links in Welcome Notification

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#62]
Hoi @larsUE, ich habe heute eine Welcome Notification in Decidim erhalten, worin es mehrere Links hat, die nicht funktionieren.

![welcome_notification](https://user-images.githubusercontent.com/222940/93332228-d3d85200-f821-11ea-80e3-7b1385f921d7.png)

Links in folgenden Texten gehen bei mir nicht:

- Gib jetzt hier deine eigene Idee für Wipkingen ein!
- Diskutiere hier über Ideen von weiteren Wipkinger*innen oder hier im Forum über grössere Visionen für das Quartier.
- Zück deine Agenda! Die Quartieridee wird durch zahlreiche Events in Wipkingen begleitet. Komm vorbei!

**Comment by larsUE** [comment]
Super, danke für den Hinweis! Mach mich dran sobald die Page wieder online ist.
