### ISSUE TITLE
Angenommene oder abgelehnte Änderungsvorschläge können nicht angezeigt werden

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/quartieridee#63]
In https://github.com/puzzle/decidim-zuerich/issues/17 ist eine erweiterte Version des Fehlers von #49 aufgefallen. Der Bug existiert auch auf der Quartieridee Produktion. Ich habe ihn auf der Integrationsumgebung behoben, bitte dort testen, dann können wir wenns passt den Stand von der Integration in die Produktion aufschalten.

**Comment by larsUE** [comment]
geflickt gemeinsam mit #49
