### ISSUE TITLE
Suchfeld funktioniert nicht

### ISSUE THREAD

**Issue by larsUE** [puzzle/quartieridee#66]
Das Suchfeld auf der Ideenseite funktioniert nicht bzw. es wird keine Suche gestartet.

**Comment by Kagemaru** [comment]
Das Problem kommt aus einem Fehler in den decidim-proposals bei einer Kombination mit decidim-amendements.

Mit der Version 0.22.0 von Decidim wurde es gefixt.

**Comment by larsUE** [comment]
@Kagemaru Super, danke! Wurde das schon auf der prod aktualisiert?

**Comment by bsantschi** [comment]
Hey Lars, nein wir haben noch nicht auf V0.22 aktualisiert. Ich melde mich dazu noch direkt per E-Mail an dich.

**Comment by larsUE** [comment]
Funktioniert mit #77
