### ISSUE TITLE
SMS-Provider anbinden

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#75]
- [ASPSMS](https://aspsms.ch/de/) anbinden
- gemäss Doku https://www.rubydoc.info/gems/decidim-verifications/0.21.0#sms-verification
- ASPSMS Credentials (siehe Cryptopus) in Umgebungsvariablen
- nur CH-Nummern zulassen (+41 hart kodieren)
- SMS Verifizierung & Workflow mit Lars testen

**Comment by carlobeltrame** [comment]
Ich habe eine erste Version in 3179bc93ae794690227c3e817ab1f7d77d4b135f umgesetzt. Das ganze muss erst noch deployed werden, und dabei müssen wir die Credentials als OpenShift Secrets einfügen. Sobald das getan ist sollten wir es mal testen @larsUE und herausfinden wie man in decidim die Verifications für bestimmte Aktionen obligatorisch macht.

Der SMS-Text kann übersetzt werden (und somit auch via term customizer angepasst), aber Umlaute funktionieren gemäss meinen Tests noch nicht, ein ü wurde immer durch eine Tilde ~ ersetzt, egal wie ich den Request an ASPSMS gesendet habe.

Die Credentials können bisher nur pro Instanz konfiguriert werden. Ich habe kurz versucht das im System Dashboard einzufügen, aber decidim ist dort bisher noch nicht sehr flexibel erweiterbar.

Man könnte (je nach Budget) noch ein, zwei Tests für die Anbindung schreiben.

**Comment by larsUE** [comment]
Cool, danke. Gib einfach Bescheid, wann ich mittesten kann. Die Verifications kannst du, nachdem sie eingerichtet wurden, mit dem Schlüsselsymbol einzelnen Komponenten zuweisen. So lassen sich auch verschiedene Authentifizierungsstufen kombinieren, ziemlich raffiniert.

<img width="284" alt="Bildschirmfoto 2021-01-13 um 15 35 41" src="https://user-images.githubusercontent.com/60926257/104466010-ffdbc800-55b4-11eb-874e-575d09ae8f3e.png">

**Comment by carlobeltrame** [comment]
Ah, interessant! Das Feature ist jetzt auf der Integrationsumgebung deployed. Du kannst also loslegen mit testen.

**Comment by larsUE** [comment]
Ich hab das Ideen-Modul auf dem Testprozess mal als Verifizierung benötigt geschaltet. Echt cool, man kann sogar auswählen, für welchen Prozessschritt eine Authentifizierung erforderlich ist. Hab mich dann verifiziert, hat alles bestens geklappt.
Als nächstes entziehe ich nun alle Berechtigungen und erstelle ein Term-Customizer Sprachset. 
@carlobeltrame: Hast du noch Ideen, wie wir die Funktion noch anderweitig testen könnten? Mehr als sich verifizieren geht ja nicht 😅

**Comment by bsantschi** [comment]
Wichtig wäre sicherlich auch die "schlechten" Fälle zu testen: falscher Code eingeben, mehrmals falscher Code eingeben, selbe Handynummer bei mehreren Accounts verwenden, etc.

**Comment by larsUE** [comment]
So, weitere Bemerkungen:

- Die Feldbeschreibung "Mobile phone number"und "Verification Code" kann ich nicht per Term-Customizer übersetzen.
- Könnten wir allenfalls noch die Länge der Nummer validieren (da ja eh nur CH-Mobilnummern aktiv sind)? Wie du bereits erwähnt hast, wir +41 und 07X validiert (und spuckt eine Fehlermeldung aus, falls nicht vorhanden). Zu lange/kurze Nummern lösen aber trotzdem den SMS-Versand aus (mit einer "Erfolgreich versendet" Meldung)
- Den SMS-Absender habe ich im Term-Customizer nicht gefunden. Hier wäre es cool, als Absender "Quartieridee" oder #{organization} statt "DECIDIM"

Sonst, mega cool!

**Comment by carlobeltrame** [comment]
> * Die Feldbeschreibung "Mobile phone number"und "Verification Code" kann ich nicht per Term-Customizer übersetzen.

Habe diese noch ergänzt, man musste die bisher nicht ausgefüllten Keys `activemodel.attributes.mobile_phone.mobile_phone_number` und `activemodel.attributes.confirmation.verification_code` verwenden.

> * Könnten wir allenfalls noch die Länge der Nummer validieren (da ja eh nur CH-Mobilnummern aktiv sind)? Wie du bereits erwähnt hast, wir +41 und 07X validiert (und spuckt eine Fehlermeldung aus, falls nicht vorhanden). Zu lange/kurze Nummern lösen aber trotzdem den SMS-Versand aus (mit einer "Erfolgreich versendet" Meldung)

Ist gemacht. Gibt halt keine schöne Fehlermeldung, nur dass irgendwas schief gelaufen ist. Aber immerhin keine falsche Erfolgs-Nachricht mehr.

> * Den SMS-Absender habe ich im Term-Customizer nicht gefunden. Hier wäre es cool, als Absender "Quartieridee" oder %{organization} statt "DECIDIM"

Ich habe das auch noch übersetzbar gemacht, unter dem Key `quartieridee.verifications.sms.aspsms_gateway.sms_originator_max_11_alphabetic_characters`. Gemäss der [ASPSMS-Dokumentation](http://json.aspsms.com/) darf dieser Name aber nur 11 Buchstaben enthalten. QUARTIERIDEE wären bereits 12.
