### ISSUE TITLE
Fehlerhafte Übersetzung

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/quartieridee#86]
In den Logs der Quartieridee Produktion ist mir folgender Fehler aufgefallen:
```
missing interpolation argument :resourcje_title in "%{author_name} hat die Idee «%{resourcje_title}» kommentiert."
```
Verfügbar sind in dieser Übersetzung folgende Platzhalter: `resource_path`, `resource_title`, `resource_url`, `participatory_space_title`, `participatory_space_url`, `author_name`, `author_nickname`, `author_path`, `author_url`. Sollte wohl `resource_title` sein.

**Comment by larsUE** [comment]
Habs mal mit dem Term Customizer überschrieben %{resource_path} ist richtig. Konnte den Key im Sprachfile jedoch nicht finden. Hoffentlich klappts so.
