### ISSUE TITLE
Stolzehüsli Newsletter Vorschau führt zu Fehler

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#87]
Maxie meldet: ich möchte gern einen Newsletter verschicken, aber wenn ich den unter Vorschau anschaue, sieht das Ganze so aus: 
![image001](https://user-images.githubusercontent.com/222940/108669121-ae402a80-74dc-11eb-8358-6d6325c4f2b4.png)

**Comment by carlobeltrame** [comment]
Grund dafür war eine Übersetzung im Term Customizer, die einen falschen Platzhalter-Namen enthielt:
> Sie haben diese E-Mail erhalten, weil Sie den %{organization}-Newsletter abonniert haben. Falls Sie das Gefühl haben, Sie kriegen zu viele E-Mails von %{organization}, können Sie Ihre Einstellungen auf <a href=\"%{link}\">deiner Benachrichtigungsseite<\/a> ändern.

Ich habe die `%{organization}` Platzhalter zu `%{organization_name}` korrigiert und gleich noch "deiner" durch "Ihrer" ersetzt:
> Sie haben diese E-Mail erhalten, weil Sie den %{organization_name}-Newsletter abonniert haben. Falls Sie das Gefühl haben, Sie kriegen zu viele E-Mails von %{organization_name}, können Sie Ihre Einstellungen auf <a href=\"%{link}\">Ihrer Benachrichtigungsseite<\/a> ändern.

Die Vorschau funktioniert jetzt wieder.
