### ISSUE TITLE
Fehlerhafte Mail-Übersetzung

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/quartieridee#89]
Auf der Quartieridee-Produktion in den Logs bin ich auf ein Problem gestossen.
Irgendwo habt ihr folgenden Text hinterlegt (wahrscheinlich im Term Customizer?):
```
<p>Hello {{{name}},</p><p>Thank you for your registration on "Quartieridee Wipkingen" and welcome!</p><p>At the moment the "Quartieridee" is in the voting phase. [...]
```
Im `{{{name}}` fehlt eine dritte schliessende geschwungene Klammer `}`. Es könnte sein, dass dadurch Personen kein Registrierungs-Mail bekommen, welche die Sprache auf Englisch eingestellt haben.

**Comment by larsUE** [comment]
Oh cool, danke! Die Nachricht kann in den Haupteinstellung angepasst werden. Ich glaub eher, die erste Klammer war zu viel (sonst sind ja alle Placeholders auch immer nur mit 2 Klammern) & habs angepasst.
