### ISSUE TITLE
evtl. zusätzlicher Antwort-Status

### ISSUE THREAD

**Issue by bsantschi** [puzzle/quartieridee#9]
Zusätzlicher Status: "Delegieren an Stadt"

**Comment by carlobeltrame** [comment]
Für den Moment benennen wir mal den existierenden Status "In Abklärung" um und schauen ob dieser den Anforderungen bereits genügt.

**Comment by bsantschi** [comment]
Abwarten, Sabeth meldet sich.

**Comment by larsUE** [comment]
Lässt sich mit Term-Customizer gut lösen. Ich habs mal auf [Meta-Decidim](https://meta.decidim.org/processes/roadmap/f/122/proposals/15920) eingegeben.
